In [1]:
import pandas as pd
import pandasql as ps

In [2]:
excel_data_socios = pd.read_excel('data_example.xlsx', sheet_name='Lista_Socios')
excel_data_arrendatario = pd.read_excel('data_example.xlsx', sheet_name='Lista_Arrendatario')

In [3]:
excel_data_socios

,socio,nombre,dni,dirección,cp,municipio,iban,telefono1,telefono2,email,votos
0,5.0,"VIVES GARCIA, JOSE",73988572-X,"ROSER, 48",3750.0,PEDREGUER,ES7530582550222720001653,0,620597627,josevivesg@hotmail.com,1
1,7.0,"MORELL SOLER, JOSE",19960500-L,"CORDOVA, 2",3750.0,PEDREGUER,ES8600811051810006225733,0,0,NaN,1
2,8.0,"BALLESTER CARRIO, VICENTE",21291130-F,"VALENCIA, 24",3750.0,PEDREGUER,ES5830582550282810001466,669740807,676197656,ballestermengualsonia@gmail.com,2
3,13.0,"SIMO FORNES, PEDRO",73985668-G,"C. VALERIA COSTA, 14",3750.0,PEDREGUER,ES0200811051890006011610,606039621,0,llesqueta1957@gmail.com,3
4,20.0,"SEGUI PEREZ (Alberques), ROSA MARIA",52787515-D,"SERPIS, 24 PTA.10",46021.0,VALENCIA,ES6801280608100100006353,963369308,965760440,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
2346,4177.0,"JULIA MOLLA, ROBERT SANTIAGO",53942999H,"ORQUIDEA, 9 D",3700.0,DENIA,ES7100811337110002164219,0,696451190,sabinekeromnes@gmail.com,1
2347,4178.0,"LLACER SERRA, MARIA EMPAR",73988600S,"LLUNA, 30 - 1º",3750.0,PEDREGUER,ES6630580990232754234436,0,638266821,emparllacerserra@gmail.com,1
2348,4179.0,"LLACER SERRA, Mª ROSARIO",73990777F,"MALAGA, 12",3730.0,XABIA,ES6100811051820006119725,0,666421941,llacer.rosser@gmail.com,1
2349,4180.0,"LLACER SERRA, JOSEP",25122446Y,"URBANIT.XALOC, 22",43540.0,S.CARLES DE LA RAPITA,ES2321000086130200865057,0,639054876,jllacer@xtec.cat,1
2350,4181.0,"LLACER SERRA, FERMIN",28992715L,"ALFONSO XIII, 13",3750.0,PEDREGUER,ES2130580990222762157091,0,686116996,fermin@llacer.as,1

In [4]:
excel_data_arrendatario

    ARRENDATARIO             NOMBRE ARRENDATARIO
0             13              SIMÓ FORNS, PEDRO
1            170      BALLESTER MASIA, JUAN LUIS
2            207         BARBER CARRIÓ, PASCUALA
3            299       CARRIO FORNES, JUAN ANGEL
4            429              COSTA FORNS, LUIS
..           ...                             ...
80          4111            ANGE BILLON, CLAUDIO
81          4125           AYET PONS, JOSE RAMON
82          4130               SERRA GIL, ISABEL
83          4142               HEIJKOOP, ADRIAAN
84          9998  FORNES SANCHO, JOSE Y JUAN BER

[85 rows x 2 columns]

In [5]:
data = ps.sqldf("""
        SELECT 
            so.*, arr.*,
            CASE WHEN arr.ARRENDATARIO IS NULL THEN 0 ELSE 1 END AS is_arrendatario
        FROM
            excel_data_socios so
                LEFT JOIN
            excel_data_arrendatario arr ON arr.ARRENDATARIO = so.socio
""")

In [6]:
data

,socio,nombre,dni,dirección,cp,municipio,iban,telefono1,telefono2,email,votos,ARRENDATARIO,NOMBRE ARRENDATARIO,is_arrendatario
0,5.0,"VIVES GARCIA, JOSE",73988572-X,"ROSER, 48",3750.0,PEDREGUER,ES7530582550222720001653,0,620597627,josevivesg@hotmail.com,1,NaN,None,0
1,7.0,"MORELL SOLER, JOSE",19960500-L,"CORDOVA, 2",3750.0,PEDREGUER,ES8600811051810006225733,0,0,None,1,NaN,None,0
2,8.0,"BALLESTER CARRIO, VICENTE",21291130-F,"VALENCIA, 24",3750.0,PEDREGUER,ES5830582550282810001466,669740807,676197656,ballestermengualsonia@gmail.com,2,NaN,None,0
3,13.0,"SIMO FORNES, PEDRO",73985668-G,"C. VALERIA COSTA, 14",3750.0,PEDREGUER,ES0200811051890006011610,606039621,0,llesqueta1957@gmail.com,3,13.0,"SIMÓ FORNS, PEDRO",1
4,20.0,"SEGUI PEREZ (Alberques), ROSA MARIA",52787515-D,"SERPIS, 24 PTA.10",46021.0,VALENCIA,ES6801280608100100006353,963369308,965760440,None,1,NaN,None,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,4177.0,"JULIA MOLLA, ROBERT SANTIAGO",53942999H,"ORQUIDEA, 9 D",3700.0,DENIA,ES7100811337110002164219,0,696451190,sabinekeromnes@gmail.com,1,NaN,None,0
2347,4178.0,"LLACER SERRA, MARIA EMPAR",73988600S,"LLUNA, 30 - 1º",3750.0,PEDREGUER,ES6630580990232754234436,0,638266821,emparllacerserra@gmail.com,1,NaN,None,0
2348,4179.0,"LLACER SERRA, Mª ROSARIO",73990777F,"MALAGA, 12",3730.0,XABIA,ES6100811051820006119725,0,666421941,llacer.rosser@gmail.com,1,NaN,None,0
2349,4180.0,"LLACER SERRA, JOSEP",25122446Y,"URBANIT.XALOC, 22",43540.0,S.CARLES DE LA RAPITA,ES2321000086130200865057,0,639054876,jllacer@xtec.cat,1,NaN,None,0
2350,4181.0,"LLACER SERRA, FERMIN",28992715L,"ALFONSO XIII, 13",3750.0,PEDREGUER,ES2130580990222762157091,0,686116996,fermin@llacer.as,1,NaN,None,0

In [7]:
sum(data['is_arrendatario'])

83